### ISSUE TITLE
Add SSL to droplet

### ISSUE THREAD

**Issue by ceelogre** [atlp-rwanda/atlp-pulse-bn#8]
# Description
Add an SSL certificate to our droplet so requests are secured.

**Comment by ceelogre** [comment]
Firefox gives a warning that it's a self-signed certificate, which one did you use?

**Comment by feyton** [comment]
I have used the openssl generated certificate since using the freeSSL certificate that is widely recognized requires a domain name to assign the certificate. Since we are using the IP Address of the droplet, we are not able to use an organization signed certificate

**Comment by ceelogre** [comment]
Ohh yeah, I forgot that we don't have a domain name. Let's see if this won't cause any CORS issue when making calls to the API.
